# Generated by Django 4.1 on 2022-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_det',
            name='currency_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
