# Generated by Django 4.1 on 2022-09-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_product_det_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_det',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
