# Generated by Django 4.1 on 2022-09-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_tag_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag_products',
            old_name='tag_products',
            new_name='taged_products',
        ),
    ]
