# Generated by Django 4.1 on 2022-09-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_rename_tag_products_tag_products_taged_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag_products',
            old_name='taged_products',
            new_name='t_products',
        ),
    ]
