# Generated by Django 4.1 on 2022-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_rename_taged_products_tag_products_t_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_products',
            name='t_products',
            field=models.CharField(max_length=225),
        ),
    ]
