# Generated by Django 4.1 on 2022-09-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_tag_products_t_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_products',
            name='t_products',
            field=models.TextField(max_length=500),
        ),
    ]
